ext-bcmath:
  type: php-extension
ext-bz2:
  type: php-extension
  depends:
    - bzip2
  php-extension:
    arg-type@unix: with-path
    arg-type@windows: with
ext-calendar:
  type: php-extension
ext-ctype:
  type: php-extension
ext-curl:
  type: php-extension
  depends:
    - curl
  depends@windows:
    - ext-zlib
    - ext-openssl
  php-extension:
    arg-type: with
ext-dba:
  type: php-extension
  suggests:
    - qdbm
  php-extension:
    arg-type: custom
ext-dom:
  type: php-extension
  depends:
    - libxml2
    - ext-xml
  php-extension:
    arg-type: '--enable-dom@shared_suffix@ --with-libxml=@build_root_path@'
    arg-type@windows: with
ext-exif:
  type: php-extension
ext-ffi:
  type: php-extension
  depends@unix:
    - libffi
  php-extension:
    arg-type@unix: '--with-ffi=@shared_suffix@ --enable-zend-signals'
    arg-type@windows: with
ext-fileinfo:
  type: php-extension
ext-filter:
  type: php-extension
ext-ftp:
  type: php-extension
  suggests:
    - ext-openssl
ext-gd:
  type: php-extension
  depends:
    - zlib
    - libpng
    - ext-zlib
  suggests:
    - libavif
    - libwebp
    - libjpeg
    - freetype
  php-extension:
    arg-type: custom
ext-gettext:
  type: php-extension
  depends:
    - gettext
  php-extension:
    arg-type: with-path
ext-gmp:
  type: php-extension
  depends:
    - gmp
  php-extension:
    arg-type: with-path
ext-iconv:
  type: php-extension
  depends@unix:
    - libiconv
  php-extension:
    arg-type@unix: with-path
    arg-type@windows: with
ext-intl:
  type: php-extension
  depends@unix:
    - icu
ext-ldap:
  type: php-extension
  depends:
    - ldap
  suggests:
    - gmp
    - libsodium
    - ext-openssl
  php-extension:
    arg-type: with-path
ext-libxml:
  type: php-extension
  depends:
    - ext-xml
  php-extension:
    build-with-php: true
    build-shared: false
    arg-type: none
ext-mbregex:
  type: php-extension
  depends:
    - onig
    - ext-mbstring
  php-extension:
    arg-type: custom
    build-shared: false
    build-static: true
    display-name: mbstring
ext-mbstring:
  type: php-extension
  php-extension:
    arg-type: custom
ext-mysqli:
  type: php-extension
  depends:
    - ext-mysqlnd
  php-extension:
    arg-type: with
    build-with-php: true
ext-mysqlnd:
  type: php-extension
  depends:
    - zlib
  php-extension:
    arg-type@unix: enable
    arg-type@windows: with
    build-with-php: true
ext-odbc:
  type: php-extension
  depends@unix:
    - unixodbc
  php-extension:
    arg-type@unix: '--with-unixODBC@shared_path_suffix@'
ext-opcache:
  type: php-extension
  php-extension:
    arg-type@unix: custom
    arg-type@windows: enable
    zend-extension: true
    display-name: 'Zend Opcache'
ext-openssl:
  type: php-extension
  depends:
    - openssl
    - zlib
    - ext-zlib
  php-extension:
    arg-type: custom
    arg-type@windows: with
    build-with-php: true
ext-password-argon2:
  type: php-extension
  depends:
    - libargon2
    - ext-openssl
  php-extension:
    arg-type: custom
    display-name: ''
ext-pcntl:
  type: php-extension
ext-pdo:
  type: php-extension
ext-pdo_mysql:
  type: php-extension
  depends:
    - ext-pdo
    - ext-mysqlnd
  php-extension:
    arg-type: with
ext-pdo_odbc:
  type: php-extension
  depends:
    - ext-pdo
    - ext-odbc
  depends@unix:
    - unixodbc
    - ext-pdo
    - ext-odbc
  php-extension:
    arg-type: custom
ext-phar:
  type: php-extension
  depends:
    - zlib
ext-readline:
  type: php-extension
  depends:
    - libedit
  php-extension:
    support:
      Windows: wip
      BSD: wip
    arg-type: '--with-libedit --without-readline'
    build-shared: false
    build-static: true
ext-session:
  type: php-extension
ext-sockets:
  type: php-extension
ext-xml:
  type: php-extension
  depends:
    - libxml2
  depends@windows:
    - libxml2
    - ext-iconv
  php-extension:
    arg-type: '--enable-xml@shared_suffix@ --with-libxml=@build_root_path@'
    arg-type@windows: with
    build-with-php: true
ext-zlib:
  type: php-extension
  depends:
    - zlib
  php-extension:
    arg-type: custom
    arg-type@windows: with
    build-with-php: true
    build-shared: false
