ext-brotli:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: kjdev/php-ext-brotli
      extract: php-src/ext/brotli
    metadata:
      license-files: [LICENSE]
      license: MIT
  depends:
    - brotli
  php-extension:
    arg-type: '--enable-brotli@shared_suffix@ --with-libbrotli'
