ext-zip:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: pecl/zip
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - libzip
  depends@windows:
    - libzip
    - zlib
    - xz
    - bzip2
  php-extension:
    arg-type: custom
    arg-type@windows: enable
