ext-uv:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: amphp/ext-uv
      extract: php-src/ext/uv
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - libuv
    - ext-sockets
  php-extension:
    arg-type: with-path
