ext-imap:
  type: php-extension
  artifact:
    source:
      type: pecl
      name: imap
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - imap
  suggests:
    - ext-openssl
  php-extension:
    arg-type: custom
