ext-uuid:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: pecl/uuid
    metadata:
      license-files: [LICENSE]
      license: LGPL-2.1-only
  depends:
    - libuuid
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: with-path
