ext-inotify:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: arnaud-lb/inotify
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  php-extension:
    os:
      - Linux
