ext-igbinary:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: igbinary/igbinary
      prefer-stable: false
      extract: php-src/ext/igbinary
    metadata:
      license-files: [COPYING]
      license: BSD-3-Clause
  suggests:
    - ext-session
    - ext-apcu
