ext-parallel:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: pecl/parallel
      extract: php-src/ext/parallel
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends@windows:
    - pthreads4w
  php-extension:
    arg-type@windows: with
