ext-excimer:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: wikimedia/mediawiki-php-excimer
      extract: php-src/ext/excimer
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  php-extension:
    os:
      - Linux
      - Darwin
