ext-igbinary:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: igbinary/igbinary
      match: tags/\d+(\.\d+)+$
      extract: php-src/ext/igbinary
    metadata:
      license-files: [COPYING]
      license: BSD-3-Clause
  suggests:
    - ext-session
    - ext-apcu
