ext-pcov:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: pecl/pcov
      extract: php-src/ext/pcov
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  php-extension:
    build-static: false
    build-shared: true
