ext-event:
  type: php-extension
  artifact:
    source:
      type: url
      url: 'https://bitbucket.org/osmanov/pecl-event/get/3.1.4.tar.gz'
      extract: php-src/ext/event
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - libevent
    - ext-openssl
  suggests:
    - ext-sockets
  php-extension:
    support:
      Windows: wip
    arg-type: custom
