ext-memcache:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: websupport-sk/pecl-memcache
      extract: php-src/ext/memcache
    metadata:
      license-files: [LICENSE]
      license: PHP-3.0
  depends:
    - ext-zlib
    - ext-session
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: '--enable-memcache@shared_suffix@ --with-zlib-dir=@build_root_path@'
