ext-imagick:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: imagick/imagick
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - imagemagick
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: custom
