ext-ast:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: nikic/php-ast
      extract: php-src/ext/ast
    metadata:
      license-files: [LICENSE]
      license: BSD-3-Clause
