ext-mysqlnd_ed25519:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: mariadb/mysqlnd_ed25519
      extract: php-src/ext/mysqlnd_ed25519
    metadata:
      license-files: [LICENSE]
      license: BSD-3-Clause
  depends:
    - ext-mysqlnd
    - libsodium
  suggests:
    - openssl
  php-extension:
    arg-type: '--with-mysqlnd_ed25519=@shared_suffix@'
    build-static: false
