ext-trader:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: php/pecl-math-trader
      extract: php-src/ext/trader
    metadata:
      license-files: [LICENSE]
      license: BSD-2-Clause
  php-extension:
    arg-type: enable
