ext-uuid:
  type: php-extension
  artifact:
    source:
      type: pecl
      name: uuid
    metadata:
      license-files: [LICENSE]
      license: LGPL-2.1-only
  depends:
    - libuuid
  php-extension:
    support:
      Windows: wip
      BSD: wip
    arg-type: with-path
