ext-ev:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: osmanov/pecl-ev
      extract: php-src/ext/ev
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - ext-sockets
  php-extension:
    arg-type@windows: with
