ext-imap:
  type: php-extension
  artifact:
    source:
      type: ghtagtar
      repo: php/pecl-mail-imap
      extract: php-src/ext/imap
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - imap
  suggests:
    - ext-openssl
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: custom
