ext-grpc:
  type: php-extension
  artifact:
    source:
      type: pie
      repo: grpc/grpc-php-ext
    metadata:
      license-files: [LICENSE]
      license: Apache-2.0
  depends:
    - grpc
  lang: cpp
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type@unix: enable-path
