ext-gearman:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: php/pecl-networking-gearman
      extract: php-src/ext/gearman
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - libgearman
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: '--with-gearman@shared_path_suffix@'
