ext-mongodb:
  type: php-extension
  artifact:
    source:
      type: ghrel
      repo: mongodb/mongo-php-driver
      match: mongodb.+\.tgz
      extract: php-src/ext/mongodb
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends@windows:
    - ext-openssl
  suggests@unix:
    - icu
    - openssl
    - zstd
    - zlib
  frameworks:
    - CoreFoundation
    - Security
  php-extension:
    arg-type@unix: custom
    arg-type@windows: '--enable-mongodb --with-mongodb-client-side-encryption'
