ext-rdkafka:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: arnaud-lb/php-rdkafka
      extract: php-src/ext/rdkafka
    metadata:
      license-files: [LICENSE]
      license: MIT
  depends:
    - librdkafka
  lang: cpp
  php-extension:
    arg-type: custom
