set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_C_FLAGS "-fPIC -fPIE")
set(VCPKG_CXX_FLAGS "-fPIC -fPIE")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DBUILD_SHARED_LIBS=OFF
    -DWITH_EXAMPLES=OFF
    -DWITH_GDK_PIXBUF=OFF
    -DBUILD_TESTING=OFF
)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/x64-linux-glibc-toolchain.cmake")