set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CXX_COMPILER /usr/bin/g++)
set(CMAKE_AR /usr/bin/ar)
set(CMAKE_LINKER /usr/bin/ld.gold)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(ENV{CFLAGS} "-fPIC -fPIE")
set(ENV{CXXFLAGS} "-fPIC -fPIE")