frankenphp:
  type: target
  artifact:
    source:
      type: ghtar
      repo: php/frankenphp
      prefer-stable: true
    metadata:
      license-files: [LICENSE]
      license: MIT
  depends:
    - php-embed
  depends@windows:
    - php-embed
    - pthreads4w
  suggests@unix:
    - brotli
    - watcher
  suggests@windows:
    - brotli
  static-bins@unix:
    - frankenphp
  static-bins@windows:
    - frankenphp.exe
  tools:
    - go-xcaddy
  tools@windows:
    - go-win
