jom:
  type: target
  artifact:
    binary:
      windows-x86_64: { type: url, url: 'https://download.qt.io/official_releases/jom/jom.zip', extract: '{pkg_root_path}/jom' }
  path@windows:
    - '{pkg_root_path}\jom'
