go-win:
  type: tool
  artifact:
    binary: custom
  env:
    GOROOT: '{pkg_root_path}/go-win'
    GOBIN: '{pkg_root_path}/go-win/bin'
    GOPATH: '{pkg_root_path}/go-win/go'
  path@windows:
    - '{pkg_root_path}/go-win/bin'
  tool:
    provides:
      - go.exe
      - gofmt.exe
    binary-subdir: go-win/bin
