ncurses:
  metadata:
    license-files:
      - COPYING
  source:
    type: filelist
    url: 'https://ftpmirror.gnu.org/gnu/ncurses/'
    regex: '/href="(?<file>ncurses-(?<version>[^"]+)\.tar\.gz)"/'
