php-src:
  metadata:
    license-files:
      - LICENSE
    license: PHP-3.01
  source:
    type: php-release
    domain: 'https://www.php.net'
  source-mirror:
    type: php-release
    domain: 'https://phpmirror.static-php.dev'
