name: Build Library Dependency Artifacts

on:
    release:
        types:
            - published
    workflow_dispatch:

jobs:
    build-release-artifacts:
        name: "Build Library Dependency Artifacts"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.1"
                operating-system:
                    - "ubuntu-latest"
                    - "macos-latest"
                library:
                    # Commented out libraries are not yet supported
                    - brotli
                    - bzip2
                    - curl
                    - freetype
                    #- glfw
                    - gmp
                    - icu
                    - imagemagick
                    - libavif
                    - libevent
                    #- libffi
                    - libiconv
                    - libjpeg
                    #- libmcrypt
                    #- libmemcached
                    - libpng
                    - libsodium
                    - libssh2
                    - libwebp
                    - libxml2
                    - libxslt
                    - libyaml
                    - libzip
                    - mcrypt
                    - ncurses
                    - nghttp2
                    - onig
                    - openssl
                    #- pkg-config
                    - postgresql
                    #- pthreads4w
                    - readline
                    - snappy
                    - sqlite
                    - xz
                    - zlib
                    - zstd

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: OS type
              id: os-type
              run: |
                  OS=""
                  if [ "${{ matrix.operating-system }}" = "ubuntu-latest" ]; then
                      OS="linux-x86_64"
                  elif [ "${{ matrix.operating-system }}" = "macos-latest" ]; then
                      OS="macos-x86_64"
                  fi
                  echo "OS=$OS" >> $GITHUB_ENV

            - name: Download SPC bin artifact
              id: download-spc-artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  branch: main
                  workflow: release-build.yml
                  name: "spc-${{ env.OS }}"

            - name: Validate SPC bin
              run: |
                  chmod +x spc
                  ./spc --version

            - id: cache-download
              uses: actions/cache@v3
              with:
                  path: downloads
                  key: php-${{ matrix.php-version }}-dependencies

            # If there's no dependencies cache, fetch sources
            - if: steps.cache-download.outputs.cache-hit != 'true'
              name: "Download sources"
              run: ./spc download --with-php=${{ matrix.php-version }} --all

            - name: "Build library: ${{ matrix.library }}"
              run: |
                  SPC_USE_SUDO=yes ./spc doctor --auto-fix
                  ./spc build:libs ${{ matrix.library }} --include-suggested

            - name: "Upload Artifact"
              uses: actions/upload-artifact@v3
              with:
                  name: php-${{ matrix.php-version }}-${{ matrix.library }}-${{ env.OS }}
                  path: |
                      buildroot/include/
                      buildroot/lib/
                  if-no-files-found: error
