name: Update Docs Config

on:
  push:
    branches:
      - main
    paths:
      - 'config/**.json'

jobs:
  update-docs-config:
    name: "Update Docs Config"
    runs-on: ubuntu-latest
    if: github.repository == 'crazywhalecc/static-php-cli'
    steps:
      - name: "Checkout static-php-cli"
        uses: actions/checkout@v4

      - name: "Checkout static-php-cli-docs"
        uses: actions/checkout@v4
        with:
          repository: static-php/static-php-cli-docs
          ref: master
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: static-php-cli-docs

      - name: "Set up Git"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: "Copy Config Files"
        run: cp -r config/* static-php-cli-docs/docs/.vitepress/config/

      - name: "Install PHP for official runners"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: 8.2
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-8.2-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-8.2-locked-composer

      - name: "Install Locked Dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Generate Extension Support List"
        run: |
          bin/spc dev:gen-ext-docs > static-php-cli-docs/docs/extensions.md

      - name: "Commit and Push Changes"
        run: |
          cd static-php-cli-docs
          git add -A
          git commit -m "Sync config files from main"
          git push origin master
